baseURL = "https://brianro.se/"
languageCode = "en-us"
title = "Brian Rose"
googleAnalytics = "UA-3149651-11"
theme = "hallo"

[Author]
    name = "Brian"

[params]
greeting = "Hi."

    [[params.links]]
        icon = "twitter"
        title = "Twitter"
        url = "https://twitter.com/brianrose"
    
    [params.colors]
        background = "#2FBDBD"
        foreground = "#FFFFFF"
        hover = "#FFCE06"